events {
    worker_connections 1024;
}

http {
    # Includes standard file types
    include /etc/nginx/mime.types;
    
    server {
        # ONLY listen on port 443 with SSL
        listen 443 ssl;
        
        # Must use 42 login domain
        server_name aysadeq.42.fr;

        # Point NGINX to the certificates
        ssl_certificate     /etc/ssl/certs/nginx.crt;
        ssl_certificate_key /etc/ssl/private/nginx.key;

        # TLSv1.2 & TLSv1.3 
        ssl_protocols       TLSv1.2 TLSv1.3;

        # Where the WordPress files are located
        root /var/www/wordpress;
        index index.php index.html;

        # How to handle normal URLs
        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # How to handle PHP files
        location ~ \.php$ {
            fastcgi_pass wordpress:9000;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
